config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'register'
             }

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get 'toggle-status'
    end
  end

  resources :projects, except: [:show]
  get 'project/:id', to: 'projects#show', as: 'project_show'
  get 'angular-projects', to: 'projects#angular'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic

  enum status: {
    draft: 0,
    published: 1,
  }
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://via.placeholder.com/#{width}x#{height}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs["name"].blank? }

  include Placeholder

  after_initialize :set_defaults

  validates_presence_of :title, :body, :main_image, :thumb_image

  scope :ruby_on_rails_projects, -> { where(subtitle: "Ruby on Rails") }

  def self.angular
    where(subtitle: "Angular")
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 400, width: 600)
    self.thumb_image ||= Placeholder.image_generator(height: 200, width: 350)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder

  after_initialize :set_defaults

  validates_presence_of :title, :percent_utilized

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: 250, width: 250)
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :project
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "Blog | Joshua Ard"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Blog status was successfully updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  included do
    before_action :current_user
  end

  def current_user
    # override devise current_user
    # super returns same devise method
    super || guest_user
  end

  def guest_user
    OpenStruct.new(
      name: "Guest User",
      first_name: "Guest",
      last_name: "User",
      email: "guest@example.com"
    )
  end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_page_defaults
  end

  def set_page_defaults
    @page_title = "Joshua Ard | Portfolio"
    @seo_keywords = "Joshua Ard portfolio"
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_params, if: :devise_controller?
  end

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:referral] if params[:referral]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @page_title = "Projects | Joshua Ard Portfolio"
  end

  def angular
    @angular_projects = Project.angular
  end

  def new
    @project = Project.new

    3.times do
      @project.technologies.build
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Project was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  private

    def project_params
      params.require(:project).
      permit(
        :title,
        :subtitle,
        :body,
        technologies_attributes: [:name]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user.is_a?(User)
      link_to "Log out", destroy_user_session_path, method: :delete
    else
      (link_to "Register", new_user_registration_path, method: :get) +
      "<br/>".html_safe +
      (link_to "Log in", new_user_session_path, method: :get)
    end
  end

  def source_helper(layout_name)
    if session[:source]
      greeting = "Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
      content_tag :div, greeting, class: "source-helper"
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.title %></td>
  <td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
  <td><%= blog.body %></td>
  <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<p>Hi <%= current_user.first_name %></p>
<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'shared/nav' %>

    <%= login_helper %>

    <%= yield %>

    <%= source_helper("application") %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p><%= number_to_phone("5555555555") %></p>
<p><%= number_to_currency("150") %></p>
<p><%= number_to_percentage("80.4") %></p>
<p><%= number_with_delimiter("41234234234") %></p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>Blog Posts</h2>
<%= @posts.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
<% end %>

<h2>Skills</h2>
<%= @skills.each do |skill| %>
  <h3><%= skill.title %></h3>
  <p><%= skill.percent_utilized %></p>
<% end %>

app/views/projects/_project.html.erb
<h2><%= link_to project.title, project_show_path(project) %></h2>
<h3><%= project.subtitle %></h3>
<p><%= project.body %></p>
<%= image_tag project.thumb_image unless project.thumb_image.nil? %>
<%= link_to "Edit", edit_project_path(project) %>
<%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/projects/angular.html.erb
<h1>Angular Projects</h1>

<% @angular_projects.each do |project| %>
  <h2><%= link_to project.title, project_show_path(project) %></h2>
  <h3><%= project.subtitle %></h3>
  <p><%= project.body %></p>
  <%= image_tag project.thumb_image unless project.thumb_image.nil? %>
  <%= link_to "Edit", edit_project_path(project) %>
  <%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= form_for(@project) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h2>

<%= link_to "New Project", new_project_path %>

<%= render partial: "project", collection: @projects %>

app/views/projects/new.html.erb
<h1>Create a new Project</h1>

<%= form_for(@project) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <ul>
      <%= form.fields_for :technologies do |technology_form| %>
        <li>
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/show.html.erb
<%= image_tag @project.main_image unless @project.thumb_image.nil? %>
<h1><%= @project.title %></h1>
<h2><%= @project.subtitle %></h2>
<p><%= @project.body %></p>

<h3>Technologies Used</h3>
<%= @project.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<div>
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Projects", projects_path %></div>
  <div><%= link_to "About Me", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
</div>